-- Generated by Drizzle Kit from the TypeScript schema. Generation 4 removes
-- the obsolete project type branch from movie-only Studio databases.
ALTER TABLE `project` DROP COLUMN `type`;--> statement-breakpoint
PRAGMA user_version = 4;
