import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const screenplay = sqliteTable('screenplay', {
  title: text('title').notNull(),
  intendedAudience: text('intended_audience'),
  targetLengthLabel: text('target_length_label'),
  estimatedMinutes: integer('estimated_minutes'),
  genrePrimary: text('genre_primary'),
  genreSecondary: text('genre_secondary'),
  tone: text('tone'),
  ratingIntent: text('rating_intent'),
  boundaries: text('boundaries'),
  logline: text('logline'),
  summary: text('summary'),
  premiseOverview: text('premise_overview'),
  centralConflict: text('central_conflict'),
  dramaticQuestion: text('dramatic_question'),
  themes: text('themes'),
  historicalBasis: text('historical_basis'),
  dramatizedElements: text('dramatized_elements'),
  storyArc: text('story_arc'),
  status: text('status'),
  researchSources: text('research_sources'),
  assumptionsMade: text('assumptions_made'),
});
