import {
  buildCastCharacterSheetContext,
  createCastCharacterSheetSpec,
  estimateCastCharacterSheetSpec,
  importCastCharacterSheetMedia,
  listCastCharacterSheetModels,
  listCastCharacterSheetSpecs,
  prepareCastCharacterSheetSpec,
  recordCastCharacterSheetRun,
  readCastCharacterSheetSpec,
  runCastCharacterSheetSpec,
  updateCastCharacterSheetSpec,
  validateCastCharacterSheetSpec,
} from '../media-generation/cast-character-sheet.js';
import {
  buildCastProfileContext,
  createCastProfileSpec,
  estimateCastProfileSpec,
  importCastProfileMedia,
  listCastProfileModels,
  listCastProfileSpecs,
  prepareCastProfileSpec,
  recordCastProfileRun,
  readCastProfileSpec,
  runCastProfileSpec,
  updateCastProfileSpec,
  validateCastProfileSpec,
} from '../media-generation/cast-profile.js';
import {
  buildLookbookImageContext,
  createLookbookImageSpec,
  estimateLookbookImageSpec,
  importLookbookImageMedia,
  listLookbookImageModels,
  listLookbookImageSpecs,
  prepareLookbookImageSpec,
  recordLookbookImageRun,
  readLookbookImageSpec,
  runLookbookImageSpec,
  updateLookbookImageSpec,
  validateLookbookImageSpec,
} from '../media-generation/lookbook-image.js';

export function createMediaGenerationServiceWiring() {
  return {
    buildLookbookImageContext,
    listLookbookImageModels,
    validateLookbookImageSpec,
    createLookbookImageSpec,
    updateLookbookImageSpec,
    readLookbookImageSpec,
    listLookbookImageSpecs,
    prepareLookbookImageSpec,
    estimateLookbookImageSpec,
    runLookbookImageSpec,
    recordLookbookImageRun,
    importLookbookImageMedia,
    buildCastCharacterSheetContext,
    listCastCharacterSheetModels,
    validateCastCharacterSheetSpec,
    createCastCharacterSheetSpec,
    updateCastCharacterSheetSpec,
    readCastCharacterSheetSpec,
    listCastCharacterSheetSpecs,
    prepareCastCharacterSheetSpec,
    estimateCastCharacterSheetSpec,
    runCastCharacterSheetSpec,
    recordCastCharacterSheetRun,
    importCastCharacterSheetMedia,
    buildCastProfileContext,
    listCastProfileModels,
    validateCastProfileSpec,
    createCastProfileSpec,
    updateCastProfileSpec,
    readCastProfileSpec,
    listCastProfileSpecs,
    prepareCastProfileSpec,
    estimateCastProfileSpec,
    runCastProfileSpec,
    recordCastProfileRun,
    importCastProfileMedia,
  };
}
