import * as characterSheet from '../media-generation/cast-character-sheet.js';
import * as castProfile from '../media-generation/cast-profile.js';
import * as castVoiceSample from '../media-generation/cast-voice-sample.js';
import * as locationHero from '../media-generation/location-hero.js';
import * as locationSheet from '../media-generation/location-environment-sheet.js';
import * as lookbookImage from '../media-generation/lookbook-image.js';
import * as lookbookSheet from '../media-generation/lookbook-sheet.js';
import * as sceneStoryboardSheet from '../media-generation/scene-storyboard-sheet.js';
import * as sharedGeneration from '../media-generation/shared-generation-service.js';
import * as estimation from '../media-generation/lifecycle/spec-estimates.js';
export function createMediaGenerationServiceWiring() {
  return {
    buildLookbookImageContext: lookbookImage.buildLookbookImageContext,
    listLookbookImageModels: lookbookImage.listLookbookImageModels,
    validateLookbookImageSpec: lookbookImage.validateLookbookImageSpec,
    createLookbookImageSpec: sharedGeneration.createMediaGenerationSpec,
    updateLookbookImageSpec: sharedGeneration.updateMediaGenerationSpec,
    readLookbookImageSpec: sharedGeneration.readMediaGenerationSpec,
    listLookbookImageSpecs: lookbookImage.listLookbookImageSpecs,
    prepareLookbookImageSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateLookbookImageSpec: estimation.estimateMediaGenerationSpec,
    runLookbookImageSpec: sharedGeneration.runMediaGenerationSpec,
    recordLookbookImageRun: lookbookImage.recordLookbookImageRun,
    importLookbookImageMedia: lookbookImage.importLookbookImageMedia,
    buildLookbookSheetContext: lookbookSheet.buildLookbookSheetContext,
    listLookbookSheetModels: lookbookSheet.listLookbookSheetModels,
    validateLookbookSheetSpec: lookbookSheet.validateLookbookSheetSpec,
    createLookbookSheetSpec: sharedGeneration.createMediaGenerationSpec,
    updateLookbookSheetSpec: sharedGeneration.updateMediaGenerationSpec,
    readLookbookSheetSpec: sharedGeneration.readMediaGenerationSpec,
    listLookbookSheetSpecs: lookbookSheet.listLookbookSheetSpecs,
    prepareLookbookSheetSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateLookbookSheetSpec: estimation.estimateMediaGenerationSpec,
    runLookbookSheetSpec: sharedGeneration.runMediaGenerationSpec,
    recordLookbookSheetRun: lookbookSheet.recordLookbookSheetRun,
    importLookbookSheetMedia: lookbookSheet.importLookbookSheetMedia,
    buildCastCharacterSheetContext: characterSheet.buildCastCharacterSheetContext, listCastCharacterSheetModels: characterSheet.listCastCharacterSheetModels,
    validateCastCharacterSheetSpec: characterSheet.validateCastCharacterSheetSpec, createCastCharacterSheetSpec: sharedGeneration.createMediaGenerationSpec,
    updateCastCharacterSheetSpec: sharedGeneration.updateMediaGenerationSpec, readCastCharacterSheetSpec: sharedGeneration.readMediaGenerationSpec,
    listCastCharacterSheetSpecs: characterSheet.listCastCharacterSheetSpecs, prepareCastCharacterSheetSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateCastCharacterSheetSpec: estimation.estimateMediaGenerationSpec, runCastCharacterSheetSpec: sharedGeneration.runMediaGenerationSpec,
    recordCastCharacterSheetRun: characterSheet.recordCastCharacterSheetRun, importCastCharacterSheetMedia: characterSheet.importCastCharacterSheetMedia,
    buildCastProfileContext: castProfile.buildCastProfileContext, listCastProfileModels: castProfile.listCastProfileModels,
    validateCastProfileSpec: castProfile.validateCastProfileSpec, createCastProfileSpec: sharedGeneration.createMediaGenerationSpec,
    updateCastProfileSpec: sharedGeneration.updateMediaGenerationSpec, readCastProfileSpec: sharedGeneration.readMediaGenerationSpec,
    listCastProfileSpecs: castProfile.listCastProfileSpecs, prepareCastProfileSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateCastProfileSpec: estimation.estimateMediaGenerationSpec, runCastProfileSpec: sharedGeneration.runMediaGenerationSpec,
    recordCastProfileRun: castProfile.recordCastProfileRun, importCastProfileMedia: castProfile.importCastProfileMedia,
    buildCastVoiceSampleContext: castVoiceSample.buildCastVoiceSampleContext,
    listCastVoiceSampleModels: castVoiceSample.listCastVoiceSampleModels,
    validateCastVoiceSampleSpec: castVoiceSample.validateCastVoiceSampleSpec,
    createCastVoiceSampleSpec: sharedGeneration.createMediaGenerationSpec,
    updateCastVoiceSampleSpec: sharedGeneration.updateMediaGenerationSpec,
    readCastVoiceSampleSpec: sharedGeneration.readMediaGenerationSpec,
    listCastVoiceSampleSpecs: castVoiceSample.listCastVoiceSampleSpecs,
    prepareCastVoiceSampleSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateCastVoiceSampleSpec: estimation.estimateMediaGenerationSpec,
    runCastVoiceSampleSpec: sharedGeneration.runMediaGenerationSpec,
    buildLocationEnvironmentSheetContext: locationSheet.buildLocationEnvironmentSheetContext,
    listLocationEnvironmentSheetModels: locationSheet.listLocationEnvironmentSheetModels,
    validateLocationEnvironmentSheetSpec: locationSheet.validateLocationEnvironmentSheetSpec,
    createLocationEnvironmentSheetSpec: sharedGeneration.createMediaGenerationSpec,
    updateLocationEnvironmentSheetSpec: sharedGeneration.updateMediaGenerationSpec,
    readLocationEnvironmentSheetSpec: sharedGeneration.readMediaGenerationSpec,
    listLocationEnvironmentSheetSpecs: locationSheet.listLocationEnvironmentSheetSpecs,
    prepareLocationEnvironmentSheetSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateLocationEnvironmentSheetSpec: estimation.estimateMediaGenerationSpec,
    runLocationEnvironmentSheetSpec: sharedGeneration.runMediaGenerationSpec,
    recordLocationEnvironmentSheetRun: locationSheet.recordLocationEnvironmentSheetRun,
    importLocationEnvironmentSheetMedia: locationSheet.importLocationEnvironmentSheetMedia,
    buildLocationHeroContext: locationHero.buildLocationHeroContext,
    listLocationHeroModels: locationHero.listLocationHeroModels,
    validateLocationHeroSpec: locationHero.validateLocationHeroSpec,
    createLocationHeroSpec: sharedGeneration.createMediaGenerationSpec,
    updateLocationHeroSpec: sharedGeneration.updateMediaGenerationSpec,
    readLocationHeroSpec: sharedGeneration.readMediaGenerationSpec,
    listLocationHeroSpecs: locationHero.listLocationHeroSpecs,
    prepareLocationHeroSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateLocationHeroSpec: estimation.estimateMediaGenerationSpec,
    runLocationHeroSpec: sharedGeneration.runMediaGenerationSpec,
    recordLocationHeroRun: locationHero.recordLocationHeroRun,
    importLocationHeroMedia: locationHero.importLocationHeroMedia,
    generateLocationHeroFromSheet: locationHero.generateLocationHeroFromSheet,
    buildSceneStoryboardSheetContext: sceneStoryboardSheet.buildSceneStoryboardSheetContext,
    listSceneStoryboardSheetModels: sceneStoryboardSheet.listSceneStoryboardSheetModels,
    validateSceneStoryboardSheetSpec: sceneStoryboardSheet.validateSceneStoryboardSheetSpec,
    createSceneStoryboardSheetSpec: sharedGeneration.createMediaGenerationSpec,
    updateSceneStoryboardSheetSpec: sharedGeneration.updateMediaGenerationSpec,
    readSceneStoryboardSheetSpec: sharedGeneration.readMediaGenerationSpec,
    listSceneStoryboardSheetSpecs: sceneStoryboardSheet.listSceneStoryboardSheetSpecs,
    prepareSceneStoryboardSheetSpec: sharedGeneration.prepareMediaGenerationSpec,
    estimateSceneStoryboardSheetSpec: estimation.estimateMediaGenerationSpec,
    runSceneStoryboardSheetSpec: sharedGeneration.runMediaGenerationSpec,
    recordSceneStoryboardSheetRun: sceneStoryboardSheet.recordSceneStoryboardSheetRun,
    importSceneStoryboardImagesMedia:
      sceneStoryboardSheet.importSceneStoryboardImagesMedia,
  };
}
