// Bundles the approved shot-design tile assets (0036) through Vite so the app
// references hashed URLs rather than runtime paths. Assets are generated by the
// project-local `$generate-assets` skill and committed under
// `shot-design-assets/generated/`. The set is still being filled in, so lookups
// for not-yet-generated files return undefined and the tile renders a
// placeholder.

const imageModules = import.meta.glob(
  './shot-design-assets/generated/images/*.png',
  { eager: true, query: '?url', import: 'default' }
) as Record<string, string>;

const motionModules = import.meta.glob(
  './shot-design-assets/generated/motion/*.mp4',
  { eager: true, query: '?url', import: 'default' }
) as Record<string, string>;

function indexByBasename(
  modules: Record<string, string>
): Record<string, string> {
  const byName: Record<string, string> = {};
  for (const [path, url] of Object.entries(modules)) {
    const basename = path.slice(path.lastIndexOf('/') + 1);
    byName[basename] = url;
  }
  return byName;
}

const imagesByName = indexByBasename(imageModules);
const motionByName = indexByBasename(motionModules);

/** Resolve a generated still tile by filename, e.g. `shot-size-close-up.png`. */
export function shotDesignImageUrl(filename: string): string | undefined {
  return imagesByName[filename];
}

/** Resolve a generated motion preview by filename, e.g. `movement-pan.mp4`. */
export function shotDesignMotionUrl(filename: string): string | undefined {
  return motionByName[filename];
}
