export {
  PROJECT_KIND,
  getStudioCorePackageInfo,
} from './package-info.js';
export type {
  ProjectKind,
  StudioCorePackageInfo,
} from './package-info.js';
export type {
  Asset,
  AssetAvailability,
  AssetFile,
  AssetLocaleContext,
  AssetReference,
  AssetSelection,
  AssetTarget,
  CastDesignAssetRoleCount,
  CastDesignResource,
  CastMember,
  CastNavigationRow,
  Clip,
  ClipDesignResource,
  ClipNavigationRow,
  ContinuityReference,
  ContinuityReferenceNavigationRow,
  Episode,
  EpisodeNavigationRow,
  MarkdownAssetContent,
  NarrativeNavigation,
  PageResponse,
  ProductionExportInput,
  ProductionExportSummary,
  ProductionExportVariant,
  ProductionExportVariantSummary,
  Project,
  ProjectCoverImage,
  ProjectCounts,
  ProjectCreateReport,
  ProjectInfo,
  ProjectInformationResource,
  ProjectLanguage,
  ProjectLibrary,
  ProjectRelativePath,
  ProjectShell,
  ProjectShellNavigation,
  ProjectSummary,
  ProjectType,
  RegisterAssetInput,
  RichTextAssetLink,
  Scene,
  SceneNavigationRow,
  Sequence,
  SequenceNavigationRow,
  StudioSelection,
  StudioSelectionContext,
  StudioSelectionContextResult,
  VisualLanguage,
  VisualLanguageCategory,
  VisualLanguageCategorySource,
  VisualLanguageNavigationRow,
  VisualLanguagePriority,
} from './project.js';
export type {
  ProjectDataErrorContract,
} from './diagnostics.js';
export type {
  ReadVisualLanguageCatalogEntryInput,
  ReadVisualLanguageCatalogInput,
  VisualLanguageCatalog,
  VisualLanguageCatalogDifficulty,
  VisualLanguageCatalogEntry,
  VisualLanguageCatalogIllustration,
} from './visual-language-catalog.js';
