export {
  PROJECT_KIND,
  getStudioCorePackageInfo,
} from './package-info.js';
export type {
  ProjectKind,
  StudioCorePackageInfo,
} from './package-info.js';
export type {
  Asset,
  AssetAvailability,
  AssetFile,
  AssetLocaleContext,
  AssetReference,
  AssetReferenceUpdateReport,
  AssetTarget,
  DisplayAssetMutationReport,
  UpdateAssetReferenceInput,
} from './assets.js';
export type * from './asset-file-generation.js';
export type {
  CastMember,
} from './cast-members.js';
export type {
  CastVoice,
  CastVoiceAttachmentCommandDocument,
  CastVoiceAttachmentDocument,
  CastVoiceAttachmentReport,
  CastVoiceElevenLabsSampleAttachmentDocument,
  CastVoiceListReport,
  CastVoiceProvider,
  CastVoiceProviderCapability,
  CastVoiceProviderRegistrationListReport,
  CastVoiceProviderRegistration,
  CastVoiceProviderRegistrationModel,
  CastVoiceProviderRegistrationReadReport,
  CastVoiceProviderRegistrationRemoveReport,
  CastVoiceProviderRegistrationWriteReport,
  CastVoiceReadReport,
  CastVoiceRemoveReport,
  CastVoiceSampleSource,
  CastVoiceValidationReport,
} from './cast-voices.js';
export type {
  CastDesignContextReport,
  CastDesignDocument,
  CastDesignListReport,
  CastDesignReadReport,
  CastDesignScope,
  CastDesignSummary,
  CastDesignWriteReport,
  CastOperationDocument,
  DepartmentCommandReport,
  DepartmentDocumentSummary,
  LocationDesignDocument,
  LocationDesignListReport,
  LocationDesignReadReport,
  LocationDesignSummary,
  LocationDesignWriteReport,
  LocationOperationDocument,
  ProductionDesignLocationContextReport,
} from './department-design.js';
export type {
  Location,
} from './locations.js';
export type {
  Scene,
  Sequence,
} from './screenplay-projection.js';
export type * from './trash.js';
export type * from './agent-media.js';
export type * from './generation.js';
export type * from './generation-preview-resource.js';
export type * from './scene-dialogue-audio-workspace.js';
export type * from './scene-beat-sheet.js';
export * from './shot-authoring.js';
export type {
  ProjectLanguage,
} from './project-languages.js';
export type {
  CastNavigationRow,
  ActNavigationRow,
  CastMemberResource,
  CastOverviewResource,
  DirectorCastReadiness,
  DirectorContextReport,
  DirectorNextStep,
  DirectorNextStepId,
  DirectorProductionDesignReadiness,
  DirectorSceneReadiness,
  DirectorScreenplayReadiness,
  DirectorVisualLanguageReadiness,
  LocationNavigationRow,
  LocationOverviewResource,
  LocationResource,
  InspirationFolderResource,
  InspirationResource,
  ProjectLookbooksResource,
  LookbookResource,
  SceneDesignResource,
  SceneNarrativeResource,
  SceneBeatSheetResource,
  SequenceSceneStoryboardPreview,
  ActStoryboardResource,
  ActStoryboardSequence,
  ActStoryboardScene,
  ActStoryboardBeat,
  ScreenplayNavigation,
  ScreenplayImageReference,
  ScreenplayImageReferenceWithHttp,
  PageResponse,
  ProjectInformationResource,
  ProjectShell,
  ProjectShellNavigation,
  ScenePanelTab,
  SceneNavigationRow,
  SequenceNavigationRow,
  SequenceResource,
  SequenceSceneRow,
  StoryArcResource,
  StudioSelection,
  StudioSelectionContext,
  StudioSelectionContextResult,
} from './resources.js';
export {
  DEFAULT_SCREENPLAY_ANALYSIS_CRITERIA,
} from './screenplay-analysis.js';
export type {
  DefaultScreenplayAnalysisCriterionKey,
  ScreenplayActAnalysis,
  ScreenplayActRole,
  ScreenplayAnalysisChange,
  ScreenplayAnalysisCommandReport,
  ScreenplayAnalysisContextAct,
  ScreenplayAnalysisContextCastMember,
  ScreenplayAnalysisContextLocation,
  ScreenplayAnalysisContextReport,
  ScreenplayAnalysisContextScene,
  ScreenplayAnalysisContextScreenplay,
  ScreenplayAnalysisContextSequence,
  ScreenplayAnalysisCriterion,
  ScreenplayAnalysisCritique,
  ScreenplayAnalysisDocument,
  ScreenplayAnalysisEvidence,
  ScreenplayAnalysisListReport,
  ScreenplayAnalysisProjectReport,
  ScreenplayAnalysisReadReport,
  ScreenplayAnalysisScoreMap,
  ScreenplayAnalysisStructureModel,
  ScreenplayAnalysisSummary,
  ScreenplayAnalysisValidationReport,
  ScreenplayAnalysisWriteReport,
  ScreenplayBeatRole,
  ScreenplayKeyBeatAnalysis,
  ScreenplaySceneAnalysis,
  ScreenplaySequenceAnalysis,
  SuggestedCriterionChange,
  SuggestedSceneAddition,
  SuggestedScenePlacement,
} from './screenplay-analysis.js';
export {
  CAMERA_ANGLE_LABELS,
  FOCUS_LABELS,
  LENS_LABELS,
  MOVE_DIRECTION_LABELS,
  MOVE_TRACK_LABELS,
  MOVEMENT_LABELS,
  RIG_LABELS,
  SHOT_SIZE_LABELS,
  SUBJECT_FRAMING_LABELS,
} from './shot-spec-labels.js';
export type {
  Project,
  ProjectCoverImage,
  ProjectCounts,
  ProjectCreateReport,
  ProjectInfo,
  ProjectRelativePath,
} from './project.js';
export type {
  ProjectLibrary,
  ProjectSummary,
} from './project-library.js';
export type {
  CameraSection,
  ColorSwatch,
  InspirationAnalysis,
  InspirationAnalysisValidationReport,
  InspirationAnalysisWriteReport,
  InspirationFolder,
  InspirationFolderDeleteReport,
  InspirationFolderListItem,
  InspirationFolderMutationReport,
  InspirationFolderReorderReport,
  InspirationFolderReport,
  InspirationFolderResourceMutationReport,
  InspirationFolderWithResolvedPath,
  InspirationImage,
  InspiredByItem,
  InspiredBySection,
  Lookbook,
  LookbookDefinitionByType,
  LookbookImage,
  LookbookImageAsset,
  LookbookImageAssetFile,
  LookbookSectionsByType,
  LookbookSheet,
  LookbookSheetAsset,
  LookbookSheetAssetFile,
  LookbookImageMutationReport,
  LookbookSheetMutationReport,
  LookbookSection,
  LookbookKind,
  ProductionLookbook,
  ProductionLookbookDefinition,
  ProductionLookbookSection,
  StoryboardLookbook,
  StoryboardLookbookDefinition,
  StoryboardLookbookSection,
  StoryboardLookbookTextSection,
  StoryboardStyleBriefSection,
  StoryboardLineAndFinishSection,
  StoryboardValueAndAccentSection,
  StoryboardGuardrailsSection,
  StoryboardMark,
  ProjectLookbooks,
  LookbookSourceInspirationsReport,
  LookbookValidationReport,
  LookbookWriteReport,
  Observation,
  PaletteSection,
  Pattern,
  PatternSection,
  TextureSection,
  ThesisSection,
  ToneMoodSection,
  VisualLanguageChange,
  VisualLanguageCommandReport,
  VisualLanguageProjectReport,
} from './visual-language.js';
export type {
  ProjectDataErrorContract,
} from './diagnostics.js';
export {
  screenplayBlockSchema,
  screenplayCreateDocumentSchema,
  screenplayDocumentSchema,
  screenplayOperationsSchema,
  screenplayReferenceSchema,
  screenplaySceneRevisionDocumentSchema,
} from './screenplay-json-schemas.js';
export {
  screenplayAnalysisDocumentSchema,
} from './screenplay-analysis-json-schemas.js';
export {
  sceneBeatSheetDocumentSchema,
  sceneBeatSheetOperationDocumentSchema,
  sceneStoryboardImagesImportDocumentSchema,
} from './scene-beat-sheet-json-schemas.js';
export {
  cameraSectionSchema as visualLanguageCameraSectionSchema,
  inspirationAnalysisDocumentSchema,
  inspirationAnalysisSectionsSchema,
  inspiredBySectionSchema as visualLanguageInspiredBySectionSchema,
  lookbookDocumentSchema,
  productionLookbookSectionsSchema,
  lookbookSourceInspirationsDocumentSchema,
  paletteSectionSchema as visualLanguagePaletteSectionSchema,
  patternSectionSchema as visualLanguagePatternSectionSchema,
  textureSectionSchema as visualLanguageTextureSectionSchema,
  thesisSectionSchema as visualLanguageThesisSectionSchema,
  toneMoodSectionSchema as visualLanguageToneMoodSectionSchema,
} from './visual-language-json-schemas.js';
export type {
  Block,
} from './screenplay.js';
export type {
  ReadVisualLanguageCatalogEntryInput,
  ReadVisualLanguageCatalogInput,
  VisualLanguageCatalog,
  VisualLanguageCatalogDifficulty,
  VisualLanguageCatalogEntry,
  VisualLanguageCatalogIllustration,
} from './visual-language-catalog.js';
